### YamlMime:Tutorial
title: Configuring your network for Microsoft 365
metadata:
  title: Configuring your network for Microsoft 365
  description: Add description
  audience: Add Audience
  level: Add level
  displayType: one-column
  ms.author: chrfox
  manager: Add manager
  ms.date: 08/15/2018
  ms.reviewer: chrfox
  ms.service: Add teams
  ms.topic: tutorial
  localization_priority: Priority
  ms.collection: Add collection
  ms.custom:
  - Add? 
  appliesto: 
  - Microsoft 365
items:
- durationInMinutes: Do we want this?
  content: |
   

   Add module description here. 

- title: Identify and differentiate Office 365 traffic
  durationInMinutes: x
  content: |

    ## 1st section. 

    Content.....

- title: Configure all your offices with local Internet connections
  durationInMinutes: x
  content: |

    ## 1st section. 

    Content.....

- title: Minimize Network traffic flow double-backs
  durationInMinutes: x
  content: |

    ## 1st section. 

    Content.....

- title: Configure edge devices for Microsoft 365 traffic bypass
  durationInMinutes: x
  content: |

    ## 1st section. 

    Content.....